In [1]:
import pandas as pd
import numpy as np

In [27]:
titanic_train=pd.read_csv(r'C:\Users\Lenovo\Desktop\workfile.csv')

In [28]:
titanic_train.tail()

PassengerId  Pclass                                       Name     Sex  \
101          993       2                         Weisz, Mr. Leopold    male   
102          994       3                         Foley, Mr. William    male   
103          995       3     Johansson Palmquist, Mr. Oskar Leander    male   
104          996       3  Thomas, Mrs. Alexander (Thamine Thelma")"  female   
105          997       3                  Holthen, Mr. Johan Martin    male   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Survived  Died  
101  27.0      1      0  228414  26.0000   NaN        S       3.0     0  
102   NaN      0      0  365235   7.7500   NaN        Q       4.0     0  
103  26.0      0      0  347070   7.7750   NaN        S       5.0     0  
104  16.0      1      1    2625   8.5167   NaN        C       5.0     0  
105  28.0      0      0  C 4001  22.5250   NaN        S       5.0     0

In [29]:
new_survived=pd.Categorical(titanic_train["Survived"])
new_survived=new_survived.rename_categories(["Died","Survived"])
new_survived.describe()

ValueError: new categories need to have the same number of items as the old categories!

In [30]:
new_Pclass=pd.Categorical(titanic_train["Pclass"],ordered=True)
new_Pclass=new_Pclass.rename_categories(["Class1","Class2","Class3"])
new_Pclass.describe()

counts     freqs
categories                  
Class1          31  0.292453
Class2          17  0.160377
Class3          58  0.547170

In [31]:
titanic_train["Pclass"]=new_Pclass

In [ ]:
titanic_train['Survived']=new_survived

In [32]:
titanic_train.head()

PassengerId  Pclass                                          Name     Sex  \
0          892  Class3                              Kelly, Mr. James    male   
1          893  Class3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894  Class2                     Myles, Mr. Thomas Francis    male   
3          895  Class3                              Wirz, Mr. Albert    male   
4          896  Class3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  Died  
0  34.5      0      0   330911   7.8292   NaN        Q       2.0     2  
1  47.0      1      0   363272   7.0000   NaN        S       3.0     3  
2  62.0      0      0   240276   9.6875   NaN        Q       4.0     4  
3  27.0      0      0   315154   8.6625   NaN        S       2.0     1  
4  22.0      1      1  3101298  12.2875   NaN        S       3.0     2

In [33]:
titanic_train["Cabin"].unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116'],
      dtype=object)

In [34]:
char_cabin=titanic_train["Cabin"].astype(str)   #convert data to str
new_Cabin=np.array([cabin[0] for cabin in char_cabin]) #take first letter
new_Cabin=pd.Categorical(new_Cabin)
new_Cabin.describe()

counts     freqs
categories                  
A                2  0.018868
B                6  0.056604
C               11  0.103774
D                4  0.037736
E                1  0.009434
F                1  0.009434
n               81  0.764151

In [35]:
titanic_train["Cabin"]=new_Cabin

In [36]:
titanic_train.tail(10)

PassengerId  Pclass                                               Name  \
96           988  Class1  Cavendish, Mrs. Tyrell William (Julia Florence...   
97           989  Class3                          Makinen, Mr. Kalle Edvard   
98           990  Class3                       Braf, Miss. Elin Ester Maria   
99           991  Class3                       Nancarrow, Mr. William Henry   
100          992  Class1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
101          993  Class2                                 Weisz, Mr. Leopold   
102          994  Class3                                 Foley, Mr. William   
103          995  Class3             Johansson Palmquist, Mr. Oskar Leander   
104          996  Class3          Thomas, Mrs. Alexander (Thamine Thelma")"   
105          997  Class3                          Holthen, Mr. Johan Martin   

        Sex   Age  SibSp  Parch             Ticket     Fare Cabin Embarked  \
96   female  76.0      1      0              19877  78.8500     C        S   
97     male  29.0      0      0  STON/O 2. 3101268   7.9250     n        S   
98   female  20.0      0      0             347471   7.8542     n        S   
99     male  33.0      0      0         A./5. 3338   8.0500     n        S   
100  female  43.0      1      0              11778  55.4417     C        C   
101    male  27.0      1      0             228414  26.0000     n        S   
102    male   NaN      0      0             365235   7.7500     n        Q   
103    male  26.0      0      0             347070   7.7750     n        S   
104  female  16.0      1      1               2625   8.5167     n        C   
105    male  28.0      0      0             C 4001  22.5250     n        S   

     Survived  Died  
96        NaN     0  
97        NaN     0  
98        NaN     0  
99        NaN     0  
100       2.0     0  
101       3.0     0  
102       4.0     0  
103       5.0     0  
104       5.0     0  
105       5.0     0

In [7]:
missing=np.where(titanic_train["Age"].isnull()==True)
missing

(array([ 10,  22,  29,  33,  36,  39,  41,  47,  54,  58,  65,  76,  83,
         84,  85,  88,  91,  93, 102], dtype=int64),)

In [6]:
titanic_train.tail(2)

PassengerId  Pclass                                       Name     Sex  \
104          996       3  Thomas, Mrs. Alexander (Thamine Thelma")"  female   
105          997       3                  Holthen, Mr. Johan Martin    male   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
104  16.0      1      1    2625   8.5167   NaN        C  
105  28.0      0      0  C 4001  22.5250   NaN        S

In [8]:
len(missing[0])

19

In [9]:
index=np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))
index

(array([53, 69], dtype=int64),)

In [10]:
titanic_train.loc[index]

PassengerId  Pclass                                 Name     Sex   Age  \
53          945       1           Fortune, Miss. Ethel Flora  female  28.0   
69          961       1  Fortune, Mrs. Mark (Mary McDougald)  female  60.0   

    SibSp  Parch Ticket   Fare        Cabin Embarked  
53      3      2  19950  263.0  C23 C25 C27        S  
69      1      4  19950  263.0  C23 C25 C27        S

In [11]:
titanic_train["Family"]=titanic_train["SibSp"]+titanic_train["Parch"]
most_family=np.where(titanic_train["Family"]==max(titanic_train["Family"]))
titanic_train.loc[most_family]

PassengerId  Pclass                                 Name     Sex   Age  \
53          945       1           Fortune, Miss. Ethel Flora  female  28.0   
55          947       3                 Rice, Master. Albert    male  10.0   
69          961       1  Fortune, Mrs. Mark (Mary McDougald)  female  60.0   

    SibSp  Parch  Ticket     Fare        Cabin Embarked  Family  
53      3      2   19950  263.000  C23 C25 C27        S       5  
55      4      1  382652   29.125          NaN        Q       5  
69      1      4   19950  263.000  C23 C25 C27        S       5

In [12]:
ser1=pd.Series([1,2,5,4],["CA","OR","NV","AZ"])
ser1

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [13]:
print("value for CA in ser1",ser1['CA'])
print("value for AZ in ser1",ser1['AZ'])
print("value for NV in ser1",ser1['NV'])

value for CA in ser1 1
value for AZ in ser1 4
value for NV in ser1 5


In [15]:
print("Indexing by number\n")
print("value for CA in ser1",ser1[0])
print("value for AZ in ser1",ser1[3])
print("value for NV in ser1",ser1[2])

Indexing by number

value for CA in ser1 1
value for AZ in ser1 4
value for NV in ser1 5


In [17]:
print("value for OR,CO,AZ\n",ser1[1:4],sep='')

value for OR,CO,AZ
OR    2
NV    5
AZ    4
dtype: int64


In [18]:
ser2=pd.Series([1,2,3,4],['CA','OR','CO','AZ'])
ser3=ser1+ser2
print(ser3)

AZ    8.0
CA    2.0
CO    NaN
NV    NaN
OR    4.0
dtype: float64


In [19]:
print(ser1*ser2)

AZ    16.0
CA     1.0
CO     NaN
NV     NaN
OR     4.0
dtype: float64


In [20]:
print(np.exp(ser1)+np.log10(ser2))

AZ    55.200210
CA     2.718282
CO          NaN
NV          NaN
OR     7.690086
dtype: float64


In [37]:
from numpy.random import randn as rn
np.random.seed(2)
matrix_data=rn(5,4)
row_labels=['A','B','C','D','E']
column_headings=['W','X','Y','Z']
df=pd.DataFrame(data=matrix_data,index=row_labels,columns=column_headings)
print(df)

          W         X         Y         Z
A -0.416758 -0.056267 -2.136196  1.640271
B -1.793436 -0.841747  0.502881 -1.245288
C -1.057952 -0.909008  0.551454  2.292208
D  0.041539 -1.117925  0.539058 -0.596160
E -0.019130  1.175001 -0.747871  0.009025


In [39]:
print(type(df[['X','Z']]))
print(df[['X','Z']])

<class 'pandas.core.frame.DataFrame'>
          X         Z
A -0.056267  1.640271
B -0.841747 -1.245288
C -0.909008  2.292208
D -1.117925 -0.596160
E  1.175001  0.009025


In [40]:
print(df.X)   #not used for multiple columns

A   -0.056267
B   -0.841747
C   -0.909008
D   -1.117925
E    1.175001
Name: X, dtype: float64


In [41]:
df.loc[['B','D'],['W','Y']]


W         Y
B -1.793436  0.502881
D  0.041539  0.539058

In [42]:
print(df>0)

       W      X      Y      Z
A  False  False  False   True
B  False  False   True  False
C  False  False   True   True
D   True  False   True  False
E  False   True  False   True


In [43]:
booldf=df>0
print(df[booldf])

          W         X         Y         Z
A       NaN       NaN       NaN  1.640271
B       NaN       NaN  0.502881       NaN
C       NaN       NaN  0.551454  2.292208
D  0.041539       NaN  0.539058       NaN
E       NaN  1.175001       NaN  0.009025


In [44]:
print(df.loc[['A','B','C']]>0)

       W      X      Y      Z
A  False  False  False   True
B  False  False   True  False
C  False  False   True   True


In [46]:
Matrix_data=np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels=['A','B','C','D','E']
column_headings=['Age','Height','Weight']

In [47]:
df=pd.DataFrame(data=Matrix_data,index=row_labels,columns=column_headings)
print(df)

   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [49]:
print(df[df['Height']>65])

   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160


In [50]:
booldf1=df['Height']>65
booldf2=df['Weight']>145

In [51]:
print(df[(booldf1)&(booldf2)])

   Age  Height  Weight
B   42      70     148
D   35      68     160


In [52]:
print(df[booldf1][['Age','Weight']])

   Age  Weight
A   22     140
B   42     148
D   35     160


In [53]:
print(df.reset_index())

  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [54]:
print(df.reset_index(drop=True))

   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


In [55]:
df['Profession']="Student Teacher Engineer Doctor Nurse".split()
print(df)

   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse


In [56]:
print(df.set_index('Profession'))

            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152
